/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abissicurallo;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.media.*;
import java.net.*;

/**
 *
 * @author murat
 */
public class FinestraIniziale extends javax.swing.JFrame {

    /**
     * Creates new form FinestraIniziale
     */
    public FinestraIniziale() {
        
 super("Demo JMF");
        play();
        Component panelControl = mp4Player.getControlPanelComponent();
        Component visualComponent = mp4Player.getVisualComponent();
        this.getContentPane().add(panelControl, BorderLayout.WEST);
        this.getContentPane().add(visualComponent, BorderLayout.CENTER);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                stop();
                System.exit(0);
            }
        });
        this.pack();
        this.setSize(new Dimension(1080, 720));
        this.setVisible(true);
        setUndecorated(true);
        initComponents();

    }
    static Player mp4Player = null;
  

    void play() {
        try {
            URL url = new URL("file", null, "C:\\Users\\murat\\OneDrive\\Documenti\\GitHub\\AbissiCurallo\\AbissiCurallo\\src\\abissicurallo\\FZNS8703.MP4");
            mp4Player = Manager.createRealizedPlayer(url);
            mp4Player.start();
        } catch (Exception e) {
            System.out.println("unable to play :" + e);
        }
    }

    void stop() {
        mp4Player.stop();
        mp4Player.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FinestraIniziale FI = new FinestraIniziale();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */


 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinestraIniziale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
